# Generated by Django 6.0 on 2026-02-01 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_app', '0003_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_backlog', to='scrum_app.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Product Backlog',
                'verbose_name_plural': 'Product Backlogs',
            },
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_backlog', to='scrum_app.sprint', verbose_name='Sprint')),
            ],
            options={
                'verbose_name': 'Sprint Backlog',
                'verbose_name_plural': 'Sprint Backlogs',
            },
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('as_a', models.CharField(blank=True, help_text='Ex: Como usuário do sistema', max_length=200, verbose_name='Como (tipo de usuário)')),
                ('i_want', models.CharField(blank=True, help_text='Ex: Eu quero fazer login', max_length=200, verbose_name='Eu quero')),
                ('so_that', models.CharField(blank=True, help_text='Ex: Para que eu possa acessar o sistema', max_length=200, verbose_name='Para que')),
                ('acceptance_criteria', models.TextField(blank=True, help_text='Critérios para considerar esta história como concluída', verbose_name='Critérios de Aceitação')),
                ('story_points', models.IntegerField(blank=True, help_text='Estimativa de esforço (Fibonacci: 1, 2, 3, 5, 8, 13...)', null=True, verbose_name='Story Points')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('TODO', 'A Fazer'), ('IN_PROGRESS', 'Em Progresso'), ('DONE', 'Concluído')], default='TODO', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('product_backlog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='scrum_app.productbacklog', verbose_name='Product Backlog')),
                ('sprint_backlog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='scrum_app.sprintbacklog', verbose_name='Sprint Backlog')),
            ],
            options={
                'verbose_name': 'User Story',
                'verbose_name_plural': 'User Stories',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
